jobs:
  create-prerelease:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        TAG: ${{ github.ref_name }}
      name: Create prerelease
      run: 'gh release create $TAG --prerelease -t $TAG

        '
name: Create Pre-release
on:
  repository_dispatch:
    types: trigger-ga___create-github-prerelease.yaml
