jobs:
  submit:
    name: Submit
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Submit Dependency Graph
      uses: advanced-security/maven-dependency-submission-action@5d0f9011b55d6268922128af45275986303459c3
name: Dependency Graph Submission of Transitive Dependencies
on:
  repository_dispatch:
    types: trigger-ga___dependency-graph-submission.yml
