concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}
jobs:
  build:
    needs: pre-checks
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      with:
        token: ${{ secrets.BOT_GITHUB_TOKEN }}
    - continue-on-error: true
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Setup Java JDK 21
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      id: update-pom-to-next-version
      uses: Alfresco/alfresco-build-tools/.github/actions/update-pom-to-next-pre-release@5d69aa4df0b14964338b43535fadb318b4ff337b
    - continue-on-error: true
      name: Update VERSION file
      run: 'echo ${{steps.update-pom-to-next-version.outputs.next-prerelease}} > VERSION

        '
    - continue-on-error: true
      name: Set VERSION env variable
      run: 'VERSION=$(cat VERSION)

        echo set VERSION=$VERSION

        echo "VERSION=$VERSION" >> $GITHUB_ENV

        '
    - continue-on-error: true
      env:
        MAVEN_CLI_OPTS: --show-version --no-transfer-progress --settings settings.xml
        MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      name: Build and Test with Maven (and maybe Deploy)
      run: mvn deploy ${{ env.MAVEN_CLI_OPTS}}
      shell: bash
    - continue-on-error: true
      name: Echo Longest Test Run
      uses: ./.github/actions/echo-longest-run
    - continue-on-error: true
      env:
        GITHUB_USERNAME: ${{ secrets.BOT_GITHUB_USERNAME }}
      name: Configure git user
      run: 'git config --global user.name $GITHUB_USERNAME

        git config --global user.email $GITHUB_USERNAME@users.noreply.github.com

        '
    - continue-on-error: true
      name: Create release tag
      run: 'git commit -am "Release $VERSION" --allow-empty

        git tag -fa $VERSION -m "Release version $VERSION"

        git push -f -q origin $VERSION

        '
    - continue-on-error: true
      name: Get branch name
      uses: Alfresco/alfresco-build-tools/.github/actions/get-branch-name@5d69aa4df0b14964338b43535fadb318b4ff337b
    - continue-on-error: true
      env:
        DEVELOPMENT_BRANCH: ${{ github.ref_name }}
      if: ${{ env.BRANCH_NAME == 'develop' }}
      name: Propagate
      uses: Alfresco/alfresco-build-tools/.github/actions/jx-updatebot-pr@5d69aa4df0b14964338b43535fadb318b4ff337b
      with:
        auto-merge: 'true'
        base-branch-name: ${{ env.DEVELOPMENT_BRANCH }}
        git-author-name: ${{ secrets.BOT_GITHUB_USERNAME }}
        git-token: ${{ secrets.BOT_GITHUB_TOKEN }}
        git-username: ${{ secrets.BOT_GITHUB_USERNAME }}
        labels: ${{ env.DEVELOPMENT_BRANCH }}
        version: ${{ env.VERSION }}
  notify:
    if: always() && failure()
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Slack Notification
      uses: Alfresco/alfresco-build-tools/.github/actions/send-slack-notification@5d69aa4df0b14964338b43535fadb318b4ff337b
      with:
        channel-id: eng-hxp-studio-activiti-gh-notifs
        token: ${{ secrets.SLACK_NOTIFICATION_BOT_TOKEN }}
  pre-checks:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      name: pre-commit
      uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@5d69aa4df0b14964338b43535fadb318b4ff337b
      with:
        skip_checkout: true
    - continue-on-error: true
      name: Ensure SHA pinned actions
      uses: zgosalvez/github-actions-ensure-sha-pinned-actions@40e45e738b3cad2729f599d8afc6ed02184e1dbd
name: Push - Validate, Build and Release
on:
  repository_dispatch:
    types: trigger-ga___main_push.yml
permissions:
  actions: write
  checks: write
  contents: write
