concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref }}
jobs:
  build:
    needs: pre-checks
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Setup Java JDK 21
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      if: ${{ contains(github.event.pull_request.labels.*.name, 'preview') }}
      name: Set preview version
      run: 'GITHUB_PR_NUMBER=PR-${{ github.event.pull_request.number }}

        echo 0.0.1-${GITHUB_PR_NUMBER}-${GITHUB_RUN_NUMBER}-SNAPSHOT > VERSION

        '
    - continue-on-error: true
      if: ${{ contains(github.event.pull_request.labels.*.name, 'preview') }}
      name: Set VERSION env variable
      run: 'VERSION=$(cat VERSION)

        echo set VERSION=$VERSION

        echo "VERSION=$VERSION" >> $GITHUB_ENV

        '
    - continue-on-error: true
      if: ${{ contains(github.head_ref, 'preview') || contains(github.event.pull_request.labels.*.name,
        'preview') }}
      name: Update pom files to the new version
      run: mvn -B versions:set -DnewVersion=$VERSION -DprocessAllModules=true -DgenerateBackupPoms=false
    - continue-on-error: true
      env:
        DO_PUSH: ${{ contains(github.event.pull_request.labels.*.name, 'preview')
          }}
      id: define_maven_command
      name: Define Maven Command
      run: "if [ $DO_PUSH == 'true' ]\nthen\n  echo \"command=deploy\" >> $GITHUB_OUTPUT\n\
        else\n  echo \"command=verify\" >> $GITHUB_OUTPUT\nfi\n"
      shell: bash
    - continue-on-error: true
      env:
        MAVEN_CLI_OPTS: --show-version --no-transfer-progress --settings settings.xml
        MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      name: Build and Test with Maven (and maybe Deploy)
      run: mvn ${{ steps.define_maven_command.outputs.command }} ${{ env.MAVEN_CLI_OPTS}}
      shell: bash
    - continue-on-error: true
      name: Echo Longest Test Run
      uses: ./.github/actions/echo-longest-run
  pre-checks:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      name: Check dependabot build
      uses: ./.github/actions/check-ext-build
    - continue-on-error: true
      name: pre-commit
      uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@5d69aa4df0b14964338b43535fadb318b4ff337b
      with:
        skip_checkout: true
    - continue-on-error: true
      name: Ensure SHA pinned actions
      uses: zgosalvez/github-actions-ensure-sha-pinned-actions@40e45e738b3cad2729f599d8afc6ed02184e1dbd
name: PR - Validate and Build
on:
  repository_dispatch:
    types: trigger-ga___main_pull.yml
permissions: read-all
